# ZSH Theme
ZSH_THEME="robbyrussell"
ZSH_TMUX_AUTOSTART=false

# Zsh Plugins
plugins=(
  git
  vi-mode
  docker
  history-substring-search
  zsh-autosuggestions
  tmux
)

# Autostart tmux on Kitty
if [ -z "$TMUX" ] && [ "$TERM" = "xterm-kitty" ]; then
  tmux attach || exec tmux new-session && exit;
fi


# Oh My ZSH
export ZSH="/Users/$USER/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

# Tmux Main Editor
export EDITOR='vim'

# Rbenv
eval "$(rbenv init -)"

# My private keys, that is on a private file (not shared)
# source ~/.private-keys

# Aliases
alias undo_not_pushed_commit="git reset HEAD~1"
alias vim=nvim
alias gcs="gh copilot suggest"

# Tmux plugins
export TMUX_PLUGIN_MANAGER_PATH="$HOME/.tmux/plugins/"

# Accept zsh-autosuggestions with Ctrl + L
bindkey '^L' autosuggest-accept

